$dirs = @(
  # Network Security sub-pages
  "app/(site)/network-security/next-generation-firewall",
  "app/(site)/network-security/hardware-firewall-innovations",
  "app/(site)/network-security/software-firewalls",
  "app/(site)/network-security/strata-cloud-manager",
  "app/(site)/network-security/sd-wan-subscription",
  "app/(site)/network-security/pan-os",
  "app/(site)/network-security/panorama",
  "app/(site)/network-security/security-subscriptions",
  "app/(site)/network-security/advanced-threat-prevention",
  "app/(site)/network-security/advanced-url-filtering",
  "app/(site)/network-security/advanced-wildfire",
  "app/(site)/network-security/advanced-dns-security",
  "app/(site)/network-security/enterprise-device-security",
  "app/(site)/network-security/medical-device-security",
  "app/(site)/network-security/strengthen-your-network-security-foundation",
  "app/(site)/network-security/simplify-network-security-management",
  "app/(site)/network-security/protect-your-extended-network",
  # SASE sub-pages
  "app/(site)/sase/access",
  "app/(site)/sase/prisma-browser",
  "app/(site)/sase/sd-wan",
  "app/(site)/sase/app-acceleration",
  "app/(site)/sase/adem",
  "app/(site)/sase/enterprise-data-loss-prevention",
  "app/(site)/sase/remote-browser-isolation",
  "app/(site)/sase/saas-security",
  "app/(site)/sase/ai-access-security",
  "app/(site)/sase/secure-work-on-any-device",
  # AI Security
  "app/(site)/ai-security/prisma-airs",
  # Cortex sub-pages
  "app/(site)/cortex/cortex-xsiam",
  "app/(site)/cortex/cortex-xdr",
  "app/(site)/cortex/cortex-xsoar",
  "app/(site)/cortex/cortex-xpanse",
  "app/(site)/cortex/managed-detection-and-response",
  "app/(site)/cortex/managed-xsiam",
  "app/(site)/cortex/fight-ai-with-ai",
  "app/(site)/cortex/cloud/application-security",
  "app/(site)/cortex/cloud/cloud-posture-security",
  "app/(site)/cortex/cloud/runtime-security",
  # Idira sub-pages
  "app/(site)/idira/human",
  "app/(site)/idira/human/privileged-access-management",
  "app/(site)/idira/human/identity-and-access-management",
  "app/(site)/idira/human/endpoint-privilege-manager",
  "app/(site)/idira/human/identity-governance",
  "app/(site)/idira/human/workforce-password-management",
  "app/(site)/idira/human/vendor-privileged-access",
  "app/(site)/idira/machine",
  "app/(site)/idira/machine/secrets-management",
  "app/(site)/idira/machine/unified-secrets-governance",
  "app/(site)/idira/machine/application-credentials-delivery",
  "app/(site)/idira/agentic",
  "app/(site)/idira/2025-magic-quadrant-report-for-pam",
  # Unit 42 sub-pages
  "app/(site)/unit42/retainer",
  "app/(site)/unit42/incident-response",
  "app/(site)/unit42/assess",
  "app/(site)/unit42/respond",
  "app/(site)/unit42/respond/managed-detection-response",
  "app/(site)/unit42/threat-intelligence-partners",
  "app/(site)/unit42/transform",
  "app/(site)/unit42/contact-unit42",
  "app/(site)/unit42/combat-risks-frontier-ai",
  # Industry
  "app/(site)/industry/public-sector",
  "app/(site)/industry/financial-services",
  "app/(site)/industry/manufacturing",
  "app/(site)/industry/healthcare",
  "app/(site)/industry/small-medium-business-portfolio",
  # Why PANW
  "app/(site)/why-paloaltonetworks/platformization",
  "app/(site)/why-paloaltonetworks/cyber-predictions",
  "app/(site)/why-paloaltonetworks/nam-cxo-portfolio",
  # Services
  "app/(site)/services/education",
  "app/(site)/services/customer-success-tools",
  # Partners
  "app/(site)/partners",
  "app/(site)/partners/nextwave-partner-portal-login",
  "app/(site)/partners/managed-security-services-provider-program",
  # Misc top-level
  "app/(site)/customers",
  "app/(site)/get-started",
  "app/(site)/resources",
  "app/(site)/resources/research/unit-42-incident-response-report",
  "app/(site)/blog",
  "app/(site)/perspectives",
  "app/(site)/cybersecurity-perspectives/cyber-perspectives-magazine",
  "app/(site)/cyberpedia",
  "app/(site)/communities",
  "app/(site)/about-us",
  "app/(site)/about-us/corporate-responsibility",
  "app/(site)/about-us/locations",
  "app/(site)/about-us/executive-briefing-program",
  "app/(site)/products/products-a-z",
  "app/(site)/podcasts/threat-vector",
  "app/(site)/quantum-safe",
  "app/(site)/tomorrow-secured",
  "app/(site)/legal-notices/privacy",
  "app/(site)/legal-notices/terms-of-use",
  "app/(site)/legal-notices/trust-center",
  "app/(site)/legal-notices/trust-center/compliance",
  "app/(site)/legal",
  "app/(site)/security-disclosure",
  "app/(site)/sitemap",
  "app/(site)/prisma/cloud",
  "app/(site)/company/newsroom",
  "app/(site)/company/press"
)

foreach ($d in $dirs) {
  New-Item -ItemType Directory -Force -Path $d | Out-Null
}

Write-Host "Done: $($dirs.Count) directories created."
